### ISSUE TITLE
Valid chart?

### ISSUE THREAD

**Issue by jbonnett92** [mcfedr/bitwarden-chart#2]
I used the command `helm repo add bitwarden https://github.com/mcfedr/bitwarden-chart.git` and got the error
```Error: Looks like "https://github.com/mcfedr/bitwarden-chart.git" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/mcfedr/bitwarden-chart.git/index.yaml : 404 Not Found```

Any ideas?

**Comment by mcfedr** [comment]
So this isnt a 'helm chart repository', rather a git repo containing a chart... anyway, you need to clone it, and then run `helm install charts/bitwarden` i.e. using the path to the local files with the chart.
